var ROUTE_INDEX = [
      { url: "/crowcash.html", label: "CrowCash", category: "Products", tags: "cash payment" },
      { url: "/crowcyber.html", label: "CrowCyber", category: "Products", tags: "cyber security" },
      { url: "/crowesg.html", label: "CrowESG", category: "Products", tags: "" },
      { url: "/crowmark.html", label: "CrowMark", category: "Products", tags: "mark branding" },
      { url: "/csrd.html", label: "CSRD Checker", category: "Products", tags: "csrd sustainability esg" },
      { url: "/tools/csrd-applicability-checker/", label: "CSRD Applicability Checker", category: "Tools", tags: "csrd sustainability esg" },
      { url: "/tools/cyber-essentials-readiness/", label: "Cyber Essentials Readiness", category: "Tools", tags: "cyber security" },
      { url: "/tools/", label: "Free Compliance Tools", category: "Tools", tags: "" },
      { url: "/tools/late-payment-calculator/", label: "Late Payment Calculator", category: "Tools", tags: "cash payment" },
      { url: "/tools/mees-risk-snapshot/", label: "MEES Risk Snapshot", category: "Tools", tags: "mees epc energy" },
      { url: "/tools/ppn-002-calculator/", label: "PPN 002 Social Value Calculator", category: "Tools", tags: "ppn social value procurement" },
      { url: "/tools/vsme-materiality-light/", label: "VSME Materiality Light", category: "Tools", tags: "vsme materiality" },
      { url: "/about.html", label: "About", category: "Pages", tags: "" },
      { url: "/demo.html", label: "Book a Demo", category: "Pages", tags: "" },
      { url: "/changelog.html", label: "Changelog", category: "Pages", tags: "" },
      { url: "/contact.html", label: "Contact", category: "Pages", tags: "" },
      { url: "/", label: "CrowAgent", category: "Pages", tags: "" },
      { url: "/products/", label: "CrowAgent Products", category: "Pages", tags: "" },
      { url: "/intel/cyber-essentials-tracker/", label: "Cyber Essentials Tracker", category: "Pages", tags: "cyber security" },
      { url: "/faq.html", label: "FAQ", category: "Pages", tags: "" },
      { url: "/intel/mees-tracker/", label: "MEES Tracker", category: "Pages", tags: "mees epc energy" },
      { url: "/404.html", label: "Page Not Found", category: "Pages", tags: "" },
      { url: "/partners.html", label: "Partners", category: "Pages", tags: "" },
      { url: "/pricing.html", label: "Pricing", category: "Pages", tags: "" },
      { url: "/resources.html", label: "Resources", category: "Pages", tags: "" },
      { url: "/roadmap.html", label: "Roadmap", category: "Pages", tags: "" },
      { url: "/blog/retrofit-cost-calculator-guide.html", label: "Commercial Property Retrofit Costs for MEES Band C Compliance", category: "Blog", tags: "mees epc energy" },
      { url: "/blog/", label: "CrowAgent Insights", category: "Blog", tags: "" },
      { url: "/blog/csrd-omnibus-i-2026.html", label: "CSRD and Omnibus I: What Changed on 18 March 2026", category: "Blog", tags: "csrd sustainability esg" },
      { url: "/blog/cyber-essentials-v3-3-danzell-2026.html", label: "Cyber Essentials v3.3 (Danzell): What Changed in April 2026", category: "Blog", tags: "cyber security" },
      { url: "/blog/epc-band-commercial-property-guide.html", label: "EPC Band Ratings: A Complete Guide for Commercial Property", category: "Blog", tags: "mees epc energy" },
      { url: "/blog/epc-register-explained.html", label: "EPC Register Explained: How to Read UK Commercial Energy Performance Certificates", category: "Blog", tags: "mees epc energy" },
      { url: "/blog/mees-commercial-property-guide.html", label: "MEES 2028: The Commercial Landlord's Complete Guide to EPC Band C", category: "Blog", tags: "mees epc energy" },
      { url: "/blog/mees-band-c-2028.html", label: "MEES Band C 2028: What Commercial Landlords Need to Know", category: "Blog", tags: "mees epc energy" },
      { url: "/blog/mees-compliance-checklist-commercial-property.html", label: "MEES Compliance Checklist for Commercial Property Managers", category: "Blog", tags: "mees epc energy" },
      { url: "/blog/mees-exemptions-guide.html", label: "MEES Exemptions: When a Commercial Property Can Legally Stay Below Band E", category: "Blog", tags: "mees epc energy" },
      { url: "/blog/mees-fine-exposure-calculator-guide.html", label: "MEES Fine Exposure Calculator: How Commercial Property Penalties Are Calculated", category: "Blog", tags: "mees epc energy" },
      { url: "/blog/mfa-mandatory-2026.html", label: "MFA Mandatory from April 2026: Guide for UK SMEs", category: "Blog", tags: "cyber security" },
      { url: "/blog/ppn-002-social-value-explained.html", label: "PPN 002 Social Value Explained: What Every UK Supplier Needs to Know", category: "Blog", tags: "ppn social value procurement" },
      { url: "/blog/ppn-002-guide.html", label: "PPN 002 Social Value: Complete Guide for UK Public Sector Suppliers", category: "Blog", tags: "ppn social value procurement" },
      { url: "/blog/ppn-002-social-value-guide.html", label: "PPN 002: The Complete Guide to Social Value Scoring for UK Bids", category: "Blog", tags: "ppn social value procurement" },
      { url: "/blog/ppn-014-cyber-essentials-guide.html", label: "PPN 014/21 Explained: Cyber Essentials for UK Public Sector", category: "Blog", tags: "cyber security ppn social value procurement" },
      { url: "/blog/social-value-portal-vs-crowmark.html", label: "Social Value Portal vs CrowMark: Which is Right for Your Business?", category: "Blog", tags: "ppn social value procurement mark branding" },
      { url: "/blog/brown-discount-commercial-property-values.html", label: "The Brown Discount: How EPC Ratings Are Affecting Commercial Property Values", category: "Blog", tags: "mees epc energy" },
      { url: "/blog/social-value-themes-explained.html", label: "The Five PPN 002 Social Value Themes: A Plain", category: "Blog", tags: "ppn social value procurement" },
      { url: "/blog/regulatory-updates-2026.html", label: "UK & EU Sustainability Regulation: Key Changes in 2026", category: "Blog", tags: "csrd sustainability esg" },
      { url: "/blog/what-is-retrofit-assessment-cost.html", label: "What is a Retrofit Assessment and How Much Does it Cost?", category: "Blog", tags: "mees epc energy" },
      { url: "/glossary/csrd.html", label: "CSRD: Corporate Sustainability Reporting Directive", category: "Glossary", tags: "csrd sustainability esg" },
      { url: "/glossary/epc-rating.html", label: "EPC Rating (Energy Performance Certificate)", category: "Glossary", tags: "mees epc energy" },
      { url: "/glossary/mees-compliance.html", label: "MEES Compliance", category: "Glossary", tags: "mees epc energy" },
      { url: "/glossary/ppn-002.html", label: "PPN 002 (Procurement Policy Note 002)", category: "Glossary", tags: "ppn social value procurement" },
      { url: "/glossary/si-2015-962.html", label: "SI 2015/962 (MEES Regulations)", category: "Glossary", tags: "mees epc energy" },
      { url: "/glossary/toms-framework.html", label: "TOMs Framework (Themes, Outcomes, Measures)", category: "Glossary", tags: "ppn social value procurement" },
      { url: "/glossary/", label: "UK Sustainability Compliance Glossary", category: "Glossary", tags: "csrd sustainability esg" },
      { url: "/tools-csrd-checker-methodology.html", label: "CSRD Checker Methodology", category: "Methodology", tags: "csrd sustainability esg" },
      { url: "/tools-cyber-essentials-readiness-methodology.html", label: "Cyber Essentials Readiness Methodology", category: "Methodology", tags: "cyber security" },
      { url: "/tools-late-payment-calculator-methodology.html", label: "Late Payment Calculator Methodology", category: "Methodology", tags: "cash payment" },
      { url: "/tools-mees-risk-snapshot-methodology.html", label: "MEES Risk Snapshot Methodology", category: "Methodology", tags: "mees epc energy" },
      { url: "/tools-ppn002-calculator-methodology.html", label: "PPN 002 Calculator Methodology", category: "Methodology", tags: "ppn social value procurement" },
      { url: "/tools-vsme-materiality-light-methodology.html", label: "VSME Materiality Light Methodology", category: "Methodology", tags: "vsme materiality" },
      { url: "/cookies.html", label: "Cookie Policy", category: "Legal", tags: "" },
      { url: "/cookie-preferences.html", label: "Cookie Preferences", category: "Legal", tags: "" },
      { url: "/privacy.html", label: "Privacy Policy", category: "Legal", tags: "" },
      { url: "/security.html", label: "Security", category: "Legal", tags: "" },
      { url: "/terms.html", label: "Terms of Service", category: "Legal", tags: "" }
    ];
