/**
 * convert-legal.js — deterministic HTML to Markdown for the four legal pages.
 *
 * WHY A SCRIPT AND NOT A MODEL. These are a privacy policy, terms of service,
 * a cookie policy and a security statement. A language model retyping them can
 * silently reword a retention period, a lawful basis or a liability cap, and
 * the result would look completely normal in review. That risk is not worth
 * taking for prose that a parser can move mechanically. Every character here is
 * either copied by the DOM or generated by a rule, and the result is verified
 * character-by-character against the source before it is written.
 *
 * WHAT IS CONVERTED, AND WHAT IS DELIBERATELY NOT.
 * Convert: h2/h3/h4, p, ul/ol/li, strong/em, a, code, br.
 * PASS THROUGH AS RAW HTML: table (these carry <caption> and header scope,
 * neither of which Markdown can express), details/summary, aside, time, sup.
 * Markdown permits embedded HTML, so passing these through keeps the exact
 * semantics rather than approximating them. Approximation is how a table
 * caption or a th[scope] quietly disappears.
 * DROP: svg (decorative icons, all aria-hidden), and the in-page nav/TOC, which
 * the Legal layout regenerates from the headings so it can never fall out of
 * sync with them.
 *
 * VERIFICATION IS THE POINT. After conversion, the visible text of the source
 * subtree and the visible text of the output must match once whitespace and
 * Markdown syntax are normalised away. Any mismatch fails the file loudly and
 * writes nothing. A converter without that check is just a faster way to lose
 * a clause.
 */
const fs = require('fs');
const path = require('path');
const { JSDOM } = require('jsdom');

const PAGES = [
  { src: 'privacy.html', slug: 'privacy' },
  { src: 'terms.html', slug: 'terms' },
  { src: 'cookies.html', slug: 'cookies' },
  { src: 'security.html', slug: 'security' },
];

const OUT_DIR = path.join('astro', 'src', 'content', 'legal');

/** Elements kept verbatim because Markdown cannot express them without loss. */
const RAW = new Set(['TABLE', 'DETAILS', 'ASIDE', 'TIME', 'SUP', 'FIGURE', 'BLOCKQUOTE']);
/** Elements removed entirely: decorative, or regenerated by the layout. */
const DROP = new Set(['SVG', 'NAV', 'SCRIPT', 'STYLE', 'BUTTON', 'FORM']);

const esc = (s) => s.replace(/([*_`[\]])/g, '\\$1');

/**
 * Elements that start a new block. Anything NOT in here is treated as inline
 * and buffered into the surrounding run of text, which is what stops a <span>
 * or a loose text node from being dropped on the floor.
 */
const BLOCK = new Set([
  'H1', 'H2', 'H3', 'H4', 'H5', 'H6',
  'P', 'UL', 'OL', 'DL', 'PRE', 'HR',
  'SECTION', 'DIV', 'ARTICLE', 'HEADER', 'FOOTER', 'MAIN',
]);

/**
 * An element passed through as raw HTML, made safe to embed in Markdown.
 *
 * TWO THINGS HAPPEN HERE, both fixing defects measured in the rendered output.
 *
 * 1. NEWLINES ARE COLLAPSED. Markdown treats a blank line as a block boundary,
 *    so a multi-line <details> block was split into several raw-HTML chunks;
 *    the browser then recovered from the unbalanced fragments by nesting, and
 *    axe reported `nested-interactive` on a <summary> that contained another
 *    <details>. The source has no nested details at all, so this was created
 *    entirely by the pipeline. Emitting one line makes it one HTML block.
 *    Rendering is unaffected because HTML collapses whitespace anyway.
 *
 * 2. TABLES GET A FOCUSABLE SCROLL CONTAINER. The prose stylesheet lets a wide
 *    table scroll horizontally, which creates a scrollable region that a
 *    keyboard user could not reach (axe: `scrollable-region-focusable`, WCAG
 *    2.1.1). The fix is the wrapper, not the table: putting tabindex and
 *    role="region" on the <table> itself would override its table semantics and
 *    break it for screen readers. The caption names the region so the landmark
 *    is not anonymous.
 */
function rawHtml(n) {
  const html = n.outerHTML.replace(/\s*\n\s*/g, ' ').trim();
  if (n.tagName.toUpperCase() !== 'TABLE') return html;
  const caption = n.querySelector('caption')?.textContent.replace(/\s+/g, ' ').trim();
  const label = caption ? `${caption} (table)` : 'Table';
  return `<div class="prose-scroll" role="region" aria-label="${label.replace(/"/g, '&quot;')}" tabindex="0">${html}</div>`;
}

/** One element, rendered as inline Markdown. */
function inlineNode(n) {
  const tag = n.tagName.toUpperCase();
  if (DROP.has(tag)) return '';
  if (RAW.has(tag)) return rawHtml(n);
  switch (tag) {
    case 'STRONG':
    case 'B':
      return `**${inline(n).trim()}**`;
    case 'EM':
    case 'I':
      return `*${inline(n).trim()}*`;
    case 'CODE':
      return `\`${n.textContent}\``;
    case 'BR':
      return '  \n';
    case 'A': {
      // Cards (anchors wrapping block content) are handled by cardGrid() at
      // block level. Anything reaching here is a genuine inline link.
      const href = n.getAttribute('href') || '';
      const text = inline(n).trim();
      return href ? `[${text}](${href})` : text;
    }
    default:
      return inline(n);
  }
}

/**
 * Join a piece onto a run, keeping a word boundary that existed in the source.
 *
 * `<span>Company</span><span>CrowAgent Ltd</span>` has no whitespace between the
 * two elements, so naive concatenation produces "CompanyCrowAgent Ltd" and
 * fuses two separate fields into one word. These are rows in a contact block
 * that CSS lays out as separate lines, so the boundary is real even though no
 * whitespace character encodes it.
 *
 * A separator is inserted only between two adjacent ELEMENTS. A text node
 * following an element is left alone, so `<strong>bold</strong>,` keeps its
 * comma tight and prose is unaffected.
 */
function join(out, piece, prevWasElement) {
  if (!piece) return out;
  const needsGap = prevWasElement && out && !/\s$/.test(out) && !/^\s/.test(piece);
  return out + (needsGap ? ' ' : '') + piece;
}

/** Inline content of an element, as Markdown. */
function inline(node) {
  let out = '';
  let prevWasElement = false;
  for (const n of node.childNodes) {
    if (n.nodeType === 3) {
      out += esc(n.textContent.replace(/\s+/g, ' '));
      prevWasElement = false;
    } else if (n.nodeType === 1) {
      out = join(out, inlineNode(n), prevWasElement);
      prevWasElement = true;
    }
  }
  return out;
}

/** True when every element child is an anchor wrapping block content. */
function isCardGrid(node) {
  const kids = [...node.children];
  if (kids.length < 2) return false;
  return kids.every(
    (k) =>
      k.tagName.toUpperCase() === 'A' &&
      [...k.children].some((c) => BLOCK.has(c.tagName.toUpperCase()))
  );
}

/**
 * A grid of card links, emitted as ONE block-level raw HTML chunk.
 *
 * The first attempt returned each card from inlineNode, which put them inside
 * the surrounding paragraph. `<p><a><h3>...</h3></a></p>` is INVALID HTML — a
 * heading cannot appear inside a paragraph — so the parser auto-closed the <p>
 * and the structure came apart: one card rendered containing nothing but an
 * aria-hidden span, which axe then correctly reported as a link with no
 * accessible name. Emitting the whole grid as its own block keeps the anchors
 * out of a paragraph entirely.
 */
function cardGrid(node) {
  const clone = node.cloneNode(true);
  clone.querySelectorAll('svg').forEach((el) => el.remove());
  clone.querySelectorAll('[class]').forEach((el) => el.removeAttribute('class'));
  clone.querySelectorAll('a').forEach((a) => a.setAttribute('class', 'prose-card'));
  clone.setAttribute('class', 'prose-cards');
  return clone.outerHTML.replace(/\s*\n\s*/g, ' ').trim();
}

/**
 * Block content of a container, as Markdown.
 *
 * Walks childNodes, NOT children. An earlier version iterated `.children`,
 * which returns elements only, so a container holding loose text alongside
 * markup lost that text without a trace: `<div><span/>Security &amp; Trust</div>`
 * emitted nothing at all. Text nodes and inline elements are now buffered into
 * an implicit paragraph and flushed whenever a genuine block element starts.
 */
function block(node, depth = 0) {
  const parts = [];
  let buf = '';
  let prevWasElement = false;
  const flush = () => {
    const t = buf.replace(/[ \t]+/g, ' ').trim();
    if (t) parts.push(t);
    buf = '';
    prevWasElement = false;
  };

  for (const n of node.childNodes) {
    if (n.nodeType === 3) {
      buf += esc(n.textContent.replace(/\s+/g, ' '));
      prevWasElement = false;
      continue;
    }
    if (n.nodeType !== 1) continue;
    const tag = n.tagName.toUpperCase();
    if (DROP.has(tag)) continue;
    if (RAW.has(tag)) {
      flush();
      parts.push(rawHtml(n));
      continue;
    }
    if (!BLOCK.has(tag)) {
      buf = join(buf, inlineNode(n), prevWasElement);
      prevWasElement = true;
      continue;
    }
    flush();
    switch (tag) {
      case 'H2':
        parts.push(`## ${inline(n).trim()}`);
        break;
      case 'H3':
        parts.push(`### ${inline(n).trim()}`);
        break;
      case 'H4':
        parts.push(`#### ${inline(n).trim()}`);
        break;
      case 'P': {
        const t = inline(n).trim();
        if (t) parts.push(t);
        break;
      }
      case 'UL':
      case 'OL': {
        const ordered = tag === 'OL';
        const items = [...n.children]
          .filter((li) => li.tagName === 'LI')
          .map((li, i) => `${ordered ? `${i + 1}.` : '-'} ${inline(li).trim()}`);
        if (items.length) parts.push(items.join('\n'));
        break;
      }
      case 'SECTION':
      case 'DIV':
      case 'ARTICLE':
      case 'HEADER':
      case 'FOOTER':
      case 'MAIN':
        {
          // A grid of card links is emitted whole, before any recursion, so the
          // anchors never end up inside a paragraph.
          if (isCardGrid(n)) {
            parts.push(cardGrid(n));
            break;
          }
          const inner = block(n, depth + 1);
          if (inner.trim()) parts.push(inner);
        }
        break;
      default: {
        const t = inline(n).trim();
        if (t) parts.push(t);
      }
    }
  }
  // Trailing inline run. Without this, text after the last block element in a
  // container is silently discarded — the same class of loss as the .children
  // walk above.
  flush();
  return parts.join('\n\n');
}

/**
 * Visible text reduced to a comparable token stream.
 *
 * An earlier version replaced Markdown syntax characters with a SPACE, which
 * invented word boundaries present in neither document: `**CrowAgent Ltd**,`
 * became "crowagent ltd ," and failed against a source reading "crowagent
 * ltd,". That is the checker being wrong rather than the conversion, and noise
 * like that is exactly what hides a real loss.
 *
 * Both sides are therefore reduced to lowercase alphanumeric tokens, keeping
 * the characters that carry meaning in this content (£ % $ €) and discarding
 * punctuation entirely. The comparison becomes symmetric and immune to markup
 * artefacts, while still failing loudly if a single WORD or NUMBER is added,
 * dropped or altered — the only class of change that matters in a legal
 * document.
 */
const visible = (s) =>
  s
    // Comments first: they can contain '>' so the tag pattern below cannot be
    // trusted to consume them, and an authoring note leaking into one side of
    // the comparison reads as invented content.
    .replace(/<!--[\s\S]*?-->/g, ' ')
    .replace(/<[^>]+>/g, ' ')                 // tags, on both sides alike
    .replace(/!?\[([^\]]*)\]\([^)]*\)/g, '$1') // markdown links -> their text
    .replace(/&nbsp;/g, ' ')
    .replace(/&amp;/g, '&')
    .replace(/&pound;/g, '£')
    .replace(/&#?\w+;/g, ' ')                 // any remaining entity
    .toLowerCase()
    .replace(/[^a-z0-9£%$€]+/g, ' ')
    .trim();

const yaml = (s) => `"${String(s).replace(/"/g, '\\"')}"`;

let failed = 0;
fs.mkdirSync(OUT_DIR, { recursive: true });

for (const { src, slug } of PAGES) {
  const dom = new JSDOM(fs.readFileSync(src, 'utf8'));
  const d = dom.window.document;

  const title = d.querySelector('title')?.textContent.trim() ?? '';
  const description = d.querySelector('meta[name="description"]')?.getAttribute('content') ?? '';
  const h1 = d.querySelector('main h1')?.textContent.replace(/\s+/g, ' ').trim() ?? '';
  const timeEl = d.querySelector('main time');
  const lastUpdated = timeEl?.getAttribute('datetime') || timeEl?.textContent.trim() || '';

  const main = d.querySelector('main');

  /*
   * The hero eyebrow becomes frontmatter too. Left in the body it rendered as a
   * stray one-line paragraph above the intro ("Legal & Data Protection"), while
   * the layout printed its own hardcoded kicker directly above it — the same
   * idea stated twice, one of them wrong. Promoting it means the kicker is the
   * page's own words.
   */
  /*
   * Identified by POSITION, not by class name. The four pages each use their
   * own prefix (`pv-eyebrow`, `tm-eyebrow`, `ca-hero-eyebrow`) and each carries
   * SEVERAL eyebrows, because section labels like "At a glance" and "Full
   * policy" use the same class as the hero one. Matching the class alone would
   * have promoted terms.html's "At a glance" into the page kicker and deleted
   * it from the section it labels.
   *
   * The hero eyebrow is the only one that appears BEFORE the <h1>. Cookies has
   * none at all, which is why this is allowed to come back empty.
   */
  const h1El = main.querySelector('h1');
  const eyebrowEl = h1El
    ? [...main.querySelectorAll('[class*="eyebrow"]')].find(
        (el) =>
          el.textContent.trim() &&
          h1El.compareDocumentPosition(el) & 2 /* DOCUMENT_POSITION_PRECEDING */
      )
    : null;
  const eyebrow = eyebrowEl?.textContent.replace(/\s+/g, ' ').trim() ?? '';
  eyebrowEl?.remove();

  // The heading and the <time> stamp become frontmatter, so remove them from
  // the body rather than rendering them twice.
  main.querySelectorAll('h1').forEach((e) => e.remove());
  if (timeEl) timeEl.closest('p')?.remove() ?? timeEl.remove();
  // Everything the converter refuses to emit is physically removed, so the
  // source side of the comparison cannot contain text the output never had.
  // BUTTON and FORM were previously skipped by block() but left in the DOM,
  // which made textContent count them and reported a phantom 16-character loss.
  main.querySelectorAll('svg, nav, script, style, button, form').forEach((e) => e.remove());

  const body = block(main).replace(/\n{3,}/g, '\n\n').trim();

  // ── Verification ──────────────────────────────────────────────────────────
  // Both sides start from HTML and run the SAME pipeline. Reading the source
  // side from textContent instead concatenated adjacent table cells with no
  // separator ("account datapurged within 30 days"), while the output side had
  // its tags replaced by spaces — a difference in the checker, not the content.
  const srcText = visible(main.innerHTML);
  const outText = visible(body);
  if (srcText !== outText) {
    failed++;
    let i = 0;
    while (i < Math.min(srcText.length, outText.length) && srcText[i] === outText[i]) i++;
    console.error(`FAIL ${slug}: text mismatch (src ${srcText.length} vs out ${outText.length})`);
    console.error(`  first divergence at ${i}`);
    console.error(`  src: ${JSON.stringify(srcText.slice(Math.max(0, i - 60), i + 120))}`);
    console.error(`  out: ${JSON.stringify(outText.slice(Math.max(0, i - 60), i + 120))}`);
    continue;
  }

  const fm = [
    '---',
    `title: ${yaml(title)}`,
    `description: ${yaml(description)}`,
    `heading: ${yaml(h1)}`,
    eyebrow ? `eyebrow: ${yaml(eyebrow)}` : null,
    lastUpdated ? `lastUpdated: ${yaml(lastUpdated)}` : null,
    '---',
    '',
  ]
    .filter(Boolean)
    .join('\n');

  fs.writeFileSync(path.join(OUT_DIR, `${slug}.md`), fm + body + '\n', 'utf8');
  console.log(
    `OK   ${slug.padEnd(9)} ${String(body.length).padStart(6)} chars  ` +
      `text verified ${srcText.length} chars  updated=${lastUpdated || '(none)'}`
  );
}

if (failed) {
  console.error(`\n${failed} file(s) failed verification. Nothing written for those.`);
  process.exit(1);
}
console.log('\nAll files verified: visible text is identical to source.');
