#!/usr/bin/env node
/* TOKEN GUARD (2026-06-01) — design-system enforcement.
 *
 * Research-backed remediation for the "898 hardcoded hex" drift (Gemini audit #2):
 * the only reliable way to keep a token system from eroding is a lint that flags
 * NEW hardcoded brand colours. This scans HAND-AUTHORED CSS for the canonical brand
 * colours used as VALUES where a var(--token) should be used instead.
 *
 * Scope (deliberate):
 *   - INCLUDES: hand-authored Assets/css/*.css (the override/patch layer).
 *   - EXCLUDES: *.compiled.css (generated by Tailwind), crowagent-brand-tokens.css
 *     (where the tokens are DEFINED), *.min.css, vendor.
 *   - SKIPS: hex inside Tailwind escaped-class selectors  .text-\[\#0CC9A8\]  (those
 *     are class names, not values) and inside rgba()/8-digit-alpha (can't 1:1 tokenise).
 *
 * Usage:  node tools/token-guard.js [--max=N]
 *   Exits non-zero if value-position brand hexes exceed --max (default: current
 *   baseline, so the count can only ratchet DOWN, never up).
 */
const fs = require('fs');
const path = require('path');

const TOKENS = {
  '#0cc9a8': 'var(--teal)',
  '#040e1a': 'var(--bg)',
  '#000212': 'var(--bg-deep)',
  '#a78bfa': 'var(--mark)',
  '#e8f0fa': 'var(--cloud)',
};
const HEX_RE = /#[0-9a-fA-F]{6}\b/g;

function handAuthoredCss() {
  const dir = 'Assets/css';
  return fs.readdirSync(dir)
    .filter(f => f.endsWith('.css'))
    .filter(f => !/\.compiled\.css$|\.min\.css$/.test(f))
    .filter(f => f !== 'crowagent-brand-tokens.css' && f !== 'sovereign-core-v2.css')
    .map(f => path.join(dir, f));
}

// Is this hex occurrence a VALUE (vs part of a Tailwind escaped-class selector)?
function isValuePosition(line, idx) {
  // selector form: .text-\[\#0CC9A8\]  — hex is preceded by \# and the line has no ':'
  // before it that starts a declaration. Cheap heuristic: if the 2 chars before the
  // '#' are '\[' or the char before is '\\', it's an escaped selector token.
  const before = line.slice(Math.max(0, idx - 2), idx);
  if (before.endsWith('\\')) return false;          // \#hex inside a selector
  // CUSTOM-PROPERTY DEFINITION (e.g. `--teal: #0CC9A8;`) — the hex IS the canonical
  // token value (source of truth), NOT a violation. Never flag/migrate these.
  if (/^\s*--[\w-]+\s*:/.test(line)) return false;
  const upto = line.slice(0, idx);
  // var() FALLBACK (e.g. `color: var(--color-ca-bg, #040E1A)`) — a defensive fallback is
  // legitimate, not drift. Skip when inside an unclosed var( on this line.
  if (/var\([^)]*$/.test(upto)) return false;
  // value position: there is a ':' earlier on the line (property: value)
  return upto.includes(':');
}

let total = 0;
const hits = [];
for (const file of handAuthoredCss()) {
  const lines = fs.readFileSync(file, 'utf8').split('\n');
  lines.forEach((line, i) => {
    let m;
    HEX_RE.lastIndex = 0;
    while ((m = HEX_RE.exec(line)) !== null) {
      const hex = m[0].toLowerCase();
      if (!TOKENS[hex]) continue;                   // only the 5 canonical brand colours
      if (!isValuePosition(line, m.index)) continue; // skip escaped-class selectors
      total++;
      hits.push({ file, line: i + 1, hex: m[0], token: TOKENS[hex] });
    }
  });
}

const argMax = (process.argv.find(a => a.startsWith('--max=')) || '').split('=')[1];
const BASELINE = argMax !== undefined ? parseInt(argMax, 10) : Infinity;

const byFile = {};
hits.forEach(h => { byFile[h.file] = (byFile[h.file] || 0) + 1; });
console.log('TOKEN GUARD — brand hexes in VALUE position (hand-authored CSS):');
Object.entries(byFile).sort((a, b) => b[1] - a[1]).forEach(([f, n]) => console.log('  ' + n.toString().padStart(4) + '  ' + f));
console.log('  ----');
console.log('  ' + total.toString().padStart(4) + '  TOTAL  (each should become ' + Object.values(TOKENS).join(' / ') + ')');

if (total > BASELINE) {
  console.error('\n✗ FAIL: ' + total + ' brand-hex values exceeds the allowed max of ' + BASELINE + '. Use the token, not the literal.');
  process.exit(1);
}
console.log('\n✓ within budget (max=' + (BASELINE === Infinity ? 'baseline-report' : BASELINE) + ')');
